exclude: '^(\.idea|\.vscode|\.vs)/'
repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: rustfmt
        name: rustfmt
        description: Format files with rustfmt.
        entry: cargo fmt
        language: system
        pass_filenames: false
        files: \.rs$
